let sample = {
  user: "James",
  data: [
    {
      name: "운전면허",
      from: "서울",
      value: "Y",
      type: "자격증",
      verify: "O",
    },
    {
      name: "토익",
      from: "토익발급기관",
      value: "888",
      type: "자격증",
      verify: "O",
    },
    {
      name: "운전면허",
      from: "서울",
      value: "Y",
      type: "자격증",
      verify: "O",
    },
    {
      name: "토익",
      from: "토익발급기관",
      value: "888",
      type: "자격증",
      verify: "O",
    },
    {
      name: "운전면허",
      from: "서울",
      value: "Y",
      type: "자격증",
      verify: "O",
    },
    {
      name: "토익",
      from: "토익발급기관",
      value: "888",
      type: "자격증",
      verify: "O",
    },

    {
      name: "오픽",
      from: "오픽처",
      value: "AL",
      verify: "O",
    },
    {
      name: "유사토익",
      from: "ㅋㅋ",
      type: "자격증",
      value: 111,
      verify: "X",
    },
    {
      name: "유사오픽",
      from: "ㅋㅋㅋ",
      value: 1112,
      type: "자격증",
      verify: "X",
    },
    {
      name: "포크레인",
      from: "ㅋㅋ",
      value: 111,
      type: "자격증",
      verify: "X",
    },
    {
      name: "서울고등학교",
      from: "zz",
      value: "졸업",
      type: "학력",
      verify: "O",
    },
    {
      name: "중앙대학교",
      from: "zz",
      value: "졸업예정",
      type: "학력",
      verify: "O",
    },
    {
      name: "장관상",
      from: "zzz",
      value: "대상",
      type: "수상내역",
      verify: "O",
    },
    {
      name: "밴드동아리",
      from: "zzz",
      value: "",
      type: "대외활동",
      verify: "X",
    },
    {
      name: "아프가니스탄 봉사",
      from: "zzz",
      value: "Y",
      type: "기타",
      verify: "X",
    },
  ],
};

export default sample;
